config/routes.rb
Compania::Application.routes.draw do
  get "pages/inicio"

  get "pages/servicios"

  get "pages/nosotros"

  get "pages/contacto"

  root :to => "pages#inicio"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def inicio
  end

  def servicios
  end

  def nosotros
  end

  def contacto
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>


   <!-- Header and Nav -->

  <div class="row">
    <div class="large-3 columns">
      <h1><img src="http://placehold.it/400x100&text=Logo"></h1>
    </div>
    <div class="large-9 columns">
      <ul class="button-group right">
        <li><%= link_to 'Inicio', pages_inicio_path, :class => "button"%></li>
        <li><%= link_to 'Servicios', pages_servicios_path, :class => "button"%></li></li>
        <li><%= link_to 'Nosotros', pages_nosotros_path, :class => "button"%></li></li>
        <li><%= link_to 'Contacto', pages_contacto_path, :class => "button"%></li></li>
      </ul>
    </div>
  </div>

  <!-- End Header and Nav -->


  <!-- First Band (Image) -->

  <div class="row">
    <div class="large-12 columns">
      <img src="http://placehold.it/1000x400&text=[img]">

      <hr>
    </div>
  </div>

<div class="row">
    <div class="large-12 columns">
<%= yield %>
</div>
</div>

  <!-- Footer -->

  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright no one at all. Go to town.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/contacto.html.erb
<h1>Pages#contacto</h1>
<p>Find me in app/views/pages/contacto.html.erb</p>

app/views/pages/inicio.html.erb
<h1>Pages#inicio</h1>
<p>Find me in app/views/pages/inicio.html.erb</p>

app/views/pages/nosotros.html.erb
<h1>Pages#nosotros</h1>
<p>Find me in app/views/pages/nosotros.html.erb</p>

app/views/pages/servicios.html.erb
<h1>Pages#servicios</h1>
<p>Find me in app/views/pages/servicios.html.erb</p>